"""
Define all errors specific to Tannner Python.

As a pattern, errors used in Tannner Python define custom error classes for different error types. This
is useful in helping the calling application discern tool errors from those generated by upstream
tools.
"""


class TannnerPython(Exception):
    """Base error class for Tannner Python."""

